# Generated by Django 3.2.4 on 2021-11-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnicalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Семантический URL')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование атрибута')),
                ('data_type', models.CharField(choices=[('text', 'Текст'), ('int', 'Целое число'), ('bool', 'Логический тип'), ('float', 'Число с плавающей точкой'), ('date', 'Дата')], max_length=6, verbose_name='Тип значения')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='ProductTechnicalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текстовое значение')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целочисленное значение')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='Числовое значение с точкой')),
                ('value_date', models.DateTimeField(blank=True, null=True, verbose_name='Значение даты и времени')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Идентификатор товара')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products_eav.producttechnicalattribute', verbose_name='Атрибут')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='values', to='contenttypes.contenttype', verbose_name='Объект продукта')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
    ]
