# Generated by Django 3.2.4 on 2021-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_eav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnicalvalue',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Значение даты и времени'),
        ),
    ]
