# Generated by Django 3.2.4 on 2021-07-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products_eav', '0002_alter_producttechnicalvalue_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnicalvalue',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='contenttypes.contenttype', verbose_name='Объект продукта'),
        ),
    ]
