# Generated by Django 3.2.4 on 2021-07-12 06:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_auto_20210623_1842'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocumentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Журнал поступления товара',
                'verbose_name_plural': 'Журналы поступления товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductDocumentExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Журнал расхода товара',
                'verbose_name_plural': 'Журналы расхода товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductAccouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('type', models.CharField(choices=[('+', 'Приход'), ('-', 'Раход')], max_length=1, verbose_name='Тип поступления')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID регистратора')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='products.product', verbose_name='Товар')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Регистратор')),
            ],
            options={
                'verbose_name': 'Учёт товаров',
                'verbose_name_plural': 'Учёт товаров',
            },
        ),
    ]
