# Generated by Django 3.2.4 on 2021-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocumentexpense',
            name='value',
            field=models.PositiveBigIntegerField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productdocumentreceipt',
            name='value',
            field=models.PositiveBigIntegerField(verbose_name='Значение'),
        ),
    ]
