# Generated by Django 3.2.4 on 2021-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_log', '0002_auto_20210712_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccouting',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productdocumentexpense',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productdocumentreceipt',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Значение'),
        ),
    ]
