# Generated by Django 3.2.4 on 2021-07-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210623_1842'),
        ('products_log', '0004_auto_20210712_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocumentexpense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productdocumentreceipt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='ProductDocumentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Актуальная дата')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Регистр цен',
                'verbose_name_plural': 'Регистры цен',
            },
        ),
    ]
