# Generated by Django 3.2.4 on 2021-07-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210623_1842'),
        ('products_log', '0005_auto_20210712_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocumentexpense',
            options={'verbose_name': 'Документ реализации товара', 'verbose_name_plural': 'Документ реализации товаров'},
        ),
        migrations.AlterModelOptions(
            name='productdocumentreceipt',
            options={'verbose_name': 'Документ поступления товара', 'verbose_name_plural': 'Документы поступления товаров'},
        ),
        migrations.AlterField(
            model_name='productdocumentexpense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_expense', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productdocumentreceipt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_receipt', to='products.product', verbose_name='Товар'),
        ),
    ]
