# Generated by Django 3.2.4 on 2021-07-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210623_1842'),
        ('products_log', '0006_auto_20210720_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccouting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='products.product', verbose_name='Товар'),
        ),
    ]
