# Generated by Django 3.2.4 on 2021-11-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_log', '0008_auto_20211105_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocumentexpense',
            name='date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
