# Generated by Django 3.2.4 on 2021-11-13 08:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Семантический URL')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание производителя')),
                ('image', models.ImageField(upload_to='upload/brand/images/%Y/%m/%d/', verbose_name='Картинка')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='META Ключевые слова')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='META Описание')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Семантический URL')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('image', models.ImageField(upload_to='upload/category/images/%Y/%m/%d/', verbose_name='Картинка')),
                ('icon', models.FileField(upload_to='upload/category/icons/%Y/%m/%d/', verbose_name='Иконка')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='META Ключевые слова')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='META Описание')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Семантический URL')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('meta_keyword', models.TextField(blank=True, null=True, verbose_name='META Ключевые слова')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='META Описание')),
                ('brand', models.ForeignKey(default='Stihl', on_delete=django.db.models.deletion.CASCADE, to='products.brand', to_field='name', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', to_field='name', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/images/images/%Y/%m/%d/', verbose_name='Картинка')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
