# Generated by Django 3.2.4 on 2021-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211123_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Артикул'),
        ),
    ]
