# Generated by Django 3.2.4 on 2021-06-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttechnicalattribute_producttechnicalvalueboolean_producttechnicalvaluefloat_producttechnicalva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttechnicalattribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='producttechnicalvalueboolean',
            options={'verbose_name': 'Булево значение', 'verbose_name_plural': 'Булево значения'},
        ),
        migrations.AlterModelOptions(
            name='producttechnicalvaluefloat',
            options={'verbose_name': 'Значение с плавающией точкой', 'verbose_name_plural': 'Значения с плавающией точкой'},
        ),
        migrations.AlterModelOptions(
            name='producttechnicalvalueinteger',
            options={'verbose_name': 'Целочисленное значение', 'verbose_name_plural': 'Целочисленные значения'},
        ),
        migrations.AlterModelOptions(
            name='producttechnicalvaluetext',
            options={'verbose_name': 'Текстовое значение', 'verbose_name_plural': 'Текстовые значения'},
        ),
    ]
