# Generated by Django 3.2.4 on 2021-06-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0004_auto_20210622_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechnicalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текстовое значение')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целочисленное значение')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='Числовое значение с запятой')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Значение даты и времени')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='Идентификатор товара')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.RemoveField(
            model_name='producttechnicalvaluefloat',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='producttechnicalvalueinteger',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='producttechnicalvaluetext',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='producttechnicalattribute',
            name='entity',
        ),
        migrations.AddField(
            model_name='producttechnicalattribute',
            name='slug',
            field=models.SlugField(default=0, verbose_name='Семантический URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductTechnicalValueBoolean',
        ),
        migrations.DeleteModel(
            name='ProductTechnicalValueFloat',
        ),
        migrations.DeleteModel(
            name='ProductTechnicalValueInteger',
        ),
        migrations.DeleteModel(
            name='ProductTechnicalValueText',
        ),
        migrations.AddField(
            model_name='producttechnicalvalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.producttechnicalattribute'),
        ),
        migrations.AddField(
            model_name='producttechnicalvalue',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Объект продукта'),
        ),
    ]
