# Generated by Django 3.2.4 on 2021-06-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210622_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnicalvalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.producttechnicalattribute', verbose_name='Атрибут'),
        ),
    ]
