# Generated by Django 3.2.4 on 2021-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producttechnicalvalue_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttechnicalattribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('int', 'Целое число'), ('bool', 'Логический тип'), ('float', 'Число с плавающей точкой'), ('date', 'Дата')], default=0, max_length=6, verbose_name='Тип значения'),
            preserve_default=False,
        ),
    ]
