# Generated by Django 3.2.4 on 2021-06-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producttechnicalattribute_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttechnicalvalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текстовое значение'),
        ),
    ]
