# Generated by Django 3.2.4 on 2021-06-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_producttechnicalvalue_value_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttechnicalvalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='producttechnicalvalue',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ProductTechnicalAttribute',
        ),
        migrations.DeleteModel(
            name='ProductTechnicalValue',
        ),
    ]
